### ISSUE TITLE
Service declaration trouble

### ISSUE THREAD

**Issue by barthy-koeln** [cometcult/CometCultBraintreeBundle#15]
I have tried implementing a service as described in the doc (with updated syntax for symfony 2.8):

```
braintree_transaction:
    class: \Braintree\Transaction
    factory: ["@comet_cult_braintree.factory", get]
    arguments: ["customer"]
```

```
$transactionService = $this->get('braintree_transaction');
$result = $transactionService::sale( ... );
```

But unfortunately it gives me this error:

`Warning: Missing argument 2 for Braintree\Customer::sale()`

Which seems to mean that the service does not take account of the class parameter.

I use version `3.16` of the `braintree_php` bundle, in which the classes are not prepended with "Braintree_" anymore. There are class aliases though, which means that I can use both:

`class: \Braintree\Transaction` or `class: \Braintree\Braintree_Transaction`

Both ways give the same error. Am I doing something wrong?

P.S.:

The following works:

```
$factory = $this->get('comet_cult_braintree.factory');
$transactionService = $factory->get('transaction');
$result = $transactionService::sale( ... );
```
